name: Test with coverage

on: [ push, pull_request ]

jobs:
  test_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Test
        run: |
          sudo apt-get install libgdal-dev
          pip install pygdal=="$(gdal-config --version).*"
          pip install -e .[test]
          pytest --cov tests/
      - name: Coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          VERBOSE: false